[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "Hx8vRhUw1Rg7nSRp7dEkpXTpwpuKFJCdHcEqinsgRKjy"

[programs.devnet]
counter = "Hx8vRhUw1Rg7nSRp7dEkpXTpwpuKFJCdHcEqinsgRKjy"

[registry]
url = "https://api.apr.dev"

# change cluster from "localnet" to "devnet" if you want to test the code in solana devnet
[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/counter.ts"
